### ISSUE TITLE
Add isBroadcast to metadata

### ISSUE THREAD

**Issue by JonasVautherin** [urbanmatrix/mavlink-kotlin#27]
I would be interested in knowing if a message is a broadcast or a targeted message before unpacking the payload. In MAVLink, a targeted message is one that has a `target_system` in its payload.

It is inconvenient when routing, because ideally the router would not spend time unpacking messages. But the information is in the XML file, so theoretically, the generator could add some kind of `isBroadcast` (or `isTargeted`, conversely) to the metadata. A router could then just extract the metadata (which implies reading only the header) and know if the message is targeted or not.

Would that be feasible? I am not sure where to start looking in the codebase :innocent:

**Comment by divyanshupundir** [comment]
This is an interesting idea. Though this library is not that well designed for routing as for endpoints. The deserialization of bytes into MAVLink message objects is done right when the bytes arrive and not lazily ([over here](https://github.com/divyanshupundir/mavlink-kotlin/blob/6a19cc374482310c9753c72b4df92a3be2cdc6d1/mavlink-kotlin/src/main/kotlin/com/divpundir/mavlink/connection/stream/StreamMavConnection.kt#L56)). Primarily because I wanted to be absolutely sure that the message is deserialised properly before sending it downstream.

The `isTargeted` flag can be added to the [`MavFrame`](https://github.com/divyanshupundir/mavlink-kotlin/blob/main/api/src/main/kotlin/com/divpundir/mavlink/api/MavFrame.kt) and the [`MavMessage.Metadata`](https://github.com/divyanshupundir/mavlink-kotlin/blob/main/api/src/main/kotlin/com/divpundir/mavlink/api/MavMessage.kt) interfaces.

But this will only be effective once the lazy deserialization mechanism is in place.

**Comment by JonasVautherin** [comment]
I see. Thanks a lot for the insights! I'll close it for now, will reopen if I get somewhere :slightly_smiling_face:.

**Comment by divyanshupundir** [comment]
Thanks for pointing it out though.

Actually, the `isTargeted` flag is the only change required in the `api` and `generator` modules. The `mavlink-kotlin` module basically implements these modules through the `MavConnection` interface.

We can also create something like a `router` module that implements the `api` and is optimized for handling something like routing.

If you want to try implementing it yourself, you can add the fields as mentioned here:

> The isTargeted flag can be added to the [MavFrame](https://github.com/divyanshupundir/mavlink-kotlin/blob/main/api/src/main/kotlin/com/divpundir/mavlink/api/MavFrame.kt) and the [MavMessage.Metadata](https://github.com/divyanshupundir/mavlink-kotlin/blob/main/api/src/main/kotlin/com/divpundir/mavlink/api/MavMessage.kt) interfaces.

For codegen in the `MavMessage.Metadata` you can simply check if any of the fields of the `MessageModel`s is `target_system` and simply add the flag to the constructor [over here](https://github.com/divyanshupundir/mavlink-kotlin/blob/6a19cc374482310c9753c72b4df92a3be2cdc6d1/generator/src/main/kotlin/com/divpundir/mavlink/generator/MessageGen.kt#L119)
